### ISSUE TITLE
Adress Boundary Error When Using Multiple Hierarchy Levels

### ISSUE THREAD

**Issue by davroes** [mjuvela/SOC#1]
Hi,
We are using SOC and LOC in our Bachelor Thesis and have encountered an issue. I might have found a bug or there could be a gap in my understanding. Could you assist us in resolving this? Thank you!

## Description
Using multiple hierarchy levels leads to an adress boundary error, causing program termination. A potential cause is a bug in Index and IndexG, where the negation and integer conversion occur in the wrong order.
## Current Behavior

Running SOC with `python ASOC.py my.ini` and a hierarchical cloud file results in:
```
 pyopencl._cl.LogicError: clFinish failed: INVALID_COMMAND_QUEUE
 fish: Job 1, 'python ASOC.py my.ini' terminated by signal SIGSEGV (Address boundary error)
```
for GPU or CPU platforms. This termination happends at the beginning of the first iteration step for the background emissions.
## Possible Solution

https://github.com/mjuvela/SOC/blob/3f6ba5704c3c57fc47f01f76261dc8535f481e11/kernel_ASOC_aux.c#L114-L116
Swapping the negation and integer conversion in the code resolves the issue. The resulting code snippet is: 
```
float link = DENS[OFF[*level]+(*ind)] ; 
// printf("   PARENT[%d] = %d\n", *ind, *(int*)(&link)) ; 
*ind       = -*(int *)&link ;  // index **WITHIN THE LEVEL*** (not global index) 
```

The reason for this is the different negation schemes between floats (leading bit) and signed integers (two's complement) when handling negation. This can result in different values as shown in the following example.
### Example
**1. Before Change** 
 - Value -1 in two's complement: `11111111` 
 - line 114: 01111111 (change leading bit to turn float negative) 
 - line 116: 01111111 -> 127 (Incorrect result) 

**2. After Change**
 - line 114: 11111111  (get the link value as float) 
 - line 116: 11111111 -> 00000001 (Correct result by negating after integer conversion)

The identical behavior is also present in `Index` within `kernel_ASOC_aux.c`, as well as in both `Index` and `IndexG` within `kernel_ASOC_map.c`.
## Steps to Reproduce

Using all the necessary files given in the example and the following my.ini and cloud description
1. Create the hierarchical cloud file using `make_hier_cloud.py`
2. Run `python ASOC.py my.ini`

Files used (my.ini, script for cloud creation and cloud data):
[Issue_additional_files.gz](https://github.com/user-attachments/files/16108952/Issue_additional_files.gz)
## Context (Environment)

The behavior was tested on the following OpenCL Platforms:
```
<pyopencl.Platform 'NVIDIA CUDA' at 0x63f95212f140>
opencl_init:
 platform  <pyopencl.Platform 'NVIDIA CUDA' at 0x63f95212f140>
 device    [<pyopencl.Device 'NVIDIA GeForce RTX 4070' on 'NVIDIA CUDA' at 0x63f95212f1b0>]
 context   <pyopencl.Context at 0x63f95211e0d0 on <pyopencl.Device 'NVIDIA GeForce RTX 4070' on 'NVIDIA CUDA' at 0x63f95212f1b0>>
 queue     <pyopencl._cl.CommandQueue object at 0x75ab5bd71c60>

```
```
<pyopencl.Platform 'NVIDIA CUDA' at 0x3220aa0>
opencl_init:
 platform  <pyopencl.Platform 'NVIDIA CUDA' at 0x3220aa0>
 device    [<pyopencl.Device 'NVIDIA GeForce GTX 1050' on 'NVIDIA CUDA' at 0x320ae70>]
 context   <pyopencl.Context at 0x3203160 on <pyopencl.Device 'NVIDIA GeForce GTX 1050' on 'NVIDIA CUDA' at 0x320ae70>>
 queue     <pyopencl._cl.CommandQueue object at 0x7ff1b5d135e0>
```
```
<pyopencl.Platform 'Intel(R) OpenCL' at 0x6179f44f2010>
opencl_init:
 platform  <pyopencl.Platform 'Intel(R) OpenCL' at 0x6179f44f2010>
 device    [<pyopencl.Device 'AMD Ryzen 9 7900X3D 12-Core Processor' on 'Intel(R) OpenCL' at 0x6179f2d772d8>]
 context   <pyopencl.Context at 0x6179f4ac84f8 on <pyopencl.Device 'AMD Ryzen 9 7900X3D 12-Core Processor' on 'Intel(R) OpenCL' at 0x6179f2d772d8>>
 queue     <pyopencl._cl.CommandQueue object at 0x736338889b70>

```
The full output of one example run:
```
read_dust: tmp.dust
ndust=1
--- SCATTERING FUNCTION: tmp.dsc
read_source_luminosities: 0 point sources
NX 32, NY 32, NZ 32 LEVELS 2, CELLS 294912
 level  0  cells  32768
 level  1  cells 262144
CLOUD READ: 32 32 32   2  294912
PACKETS: PSPAC 0   BGPAC 1001472  CLPAC 0  DFPAC 0
PS_METHOD=0, WITH_ABU=0, WITH_MSF=0
*** MIRROR ***  0
opencl_init
--------------------------------------------------------------------------------
opencl_init,  try platforms [0 1 2 3 4]
<pyopencl.Platform 'NVIDIA CUDA' at 0x6179f4ad7310>
<pyopencl.Platform 'Intel(R) OpenCL' at 0x6179f44f2010>
opencl_init:
 platform  <pyopencl.Platform 'Intel(R) OpenCL' at 0x6179f44f2010>
 device    [<pyopencl.Device 'AMD Ryzen 9 7900X3D 12-Core Processor' on 'Intel(R) OpenCL' at 0x6179f2d772d8>]
 context   <pyopencl.Context at 0x6179f4ac84f8 on <pyopencl.Device 'AMD Ryzen 9 7900X3D 12-Core Processor' on 'Intel(R) OpenCL' at 0x6179f2d772d8>>
 queue     <pyopencl._cl.CommandQueue object at 0x736338889b70>
--------------------------------------------------------------------------------
/home/davroes/.local/share/virtualenvs/Bachelor-R-qw4wOs/lib/python3.12/site-packages/pyopencl/cache.py:417: CompilerWarning: From-source build succeeded, but resulted in non-empty logs:
Build on <pyopencl.Device 'AMD Ryzen 9 7900X3D 12-Core Processor' on 'Intel(R) OpenCL' at 0x6179f2d772d8> succeeded, but said:

Compilation started
Compilation done
Linking started
Linking done
Device build started
Options used by backend compiler: -D NX=32 -D NY=32 -D NZ=32 -D BINS=2500 -D WITH_ALI=0 -D PS_METHOD=0 -D FACTOR=1.0000e+20f -D CELLS=294912 -D AREA=6144 -D NO_PS=1 -D WITH_ABU=0 -D ROI_MAP=0 -D MAX_SPLIT=4300 -D SELEM=0 -D ROI_STEP=0 -D ROI_NSIDE=16 -D WITH_ROI_LOAD=0 -D WITH_ROI_SAVE=0 -D AXY=0.16667f -D AXZ=0.16667f -D AYZ=0.16667f -D LEVELS=2 -D LENGTH=6.17136e+16f -I/home/davroes/Programming/Bachelor/SOC_test/SOC -D DO_SPLIT=0 -D POLSTAT=0 -D SW_A=-1.000e+00f -D SW_B=0.000e+00f -D STEP_WEIGHT=0 -D DIR_WEIGHT=-1 -D DW_A=0.000e+00f -D LEVEL_THRESHOLD=0 -D POLRED=0 -D p00=0.2000f -D MINLOS=-1.000e+00f -D MAXLOS=1.000e+10f -D FFS=1 -D NODIR=1 -D USE_EMWEIGHT=0 -D SAVE_INTENSITY=0 -D NOABSORBED=1 -D INTERPOLATE=0 -D ADHOC=1.00000e+00f -D HPBG_WEIGHTED=0 -D WITH_MSF=0 -D NDUST=1 -D OPT_IS_HALF=0 -D POL_RHO_WEIGHT=0 -D MAP_INTERPOLATION=0 -D MIRROR=0 -cl-mad-enable -cl-no-signed-zeros -cl-finite-math-only -D NSIDE=128 -I /home/davroes/.local/share/virtualenvs/Bachelor-R-qw4wOs/lib/python3.12/site-packages/pyopencl/cl
Device build done
Kernel "ZeroAMC" was successfully vectorized (16)
Kernel "Parents" was successfully vectorized (16)
Kernel "AverageDensity" was successfully vectorized (16)
Kernel "EqTemperature" was successfully vectorized (16)
Kernel "Emission" was successfully vectorized (16)
Kernel "Emission2" was successfully vectorized (16)
Kernel "SimRAM_PB" was not vectorized
Kernel "SimRAM_HP" was not vectorized
Kernel "SimRAM_CL" was not vectorized
Done.
  prg.build(options_bytes, [devices[i] for i in to_be_built_indices])
EMWEI 0, SAVE_INTENSITY 0
LOCAL 8, GLOBAL 32768
Reading emitted file emitted.data
Emitted file has cells 294912, freq 44 -> now 294912 cells, 44 freq
Mapping E -> T calculated on host: 0.276 seconds
Emin= 1.686e-12, Emax= 1.087e+06, kE= 1.001368,  NE= 30000, kE**(NE-1)= 6.443e+17
TTT 1.000e+00 - 1.601e+03
=== SIMULATE CONSTANT SOURCES II=0
=== SIMULATE CONSTANT SOURCES II=1
=== BG: BGPAC 983040, BATCH 20, GLOBAL 49152, LOCAL 8 ===
  FREQ   1/ 44   1.499e+11   BG   7.7419e-02  PS   0.0000e+00   TW  3.069e+21fish: Job 1, 'python ASOC.py my.ini' terminated by signal SIGSEGV (Address boundary error)
```

If additional information is needed, please let me know and I will provide it promptly.

**Comment by mjuvela** [comment]
I think the idea of storing an integer index _i_ was to first interpret that as a 32 bit float _x_  and only then negate and store the -_x_ in the array (with the knowledge that all values >0 are real densities, not these encoded links). To get back the integer, one would take the array element (float32), negate that, and then interpret the bits as int32. I think this conversion should be ok, as long as that is consistent in both directions (int->float->int). Perhaps yous just created the hierarchy file by putting the minus on the integer rather than on the float? When working in Python, I have used routines

```
import ctypes
def I2F(i):
    return ctypes.c_float.from_buffer(ctypes.c_int(i)).value

def F2I(x):
    return ctypes.c_int.from_buffer(ctypes.c_float(x)).value

```

Also with these, an integer _i_ is stored into a float32 array as  `H[j] = -I2F(i)`, minus operating on the float.

First, are you sure all of the actual density values are non-negative? That is one way of getting segmentation error, when SOC tries to interpret those as non-existing indices. Second, confirm that the "links" are encoded as above and are to cells that exist (always index of the first of the eight child cells). Third, if problem persists, you could share a small example of hierarchy file so that I could also have a look at it.

**Comment by davroes** [comment]
Ah, yes, that was my mistake. I negated the integers before converting them into floats, instead of the other way around. Using the correct conversion, it works without any issues. Thank you very much for the quick and helpful response. I don't know how I didn't think of interpreting it this way. In hindsight, looking at the code I thought had a bug, it's pretty obvious that the error was in my conversion and I shoud have tested it. 

Have a nice weekend!
